# Site settings
title: Rhys Bower
author: Rhys Bower
email: bowerrhys@gmail.com
description: >
  I'm an aspiring local developer
  working on a number of programming
  projects. I will be studying Computer Science at UBC next year.
image: /img/profile.jpg
copyright: Copyright © 2015 Rhys Bower. All rights reserved.
permalink: /:year/:month/:title/
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
