# Site settings
title: Rhys Bower
author: Rhys Bower
email: bowerrhys@gmail.com
description: >
  Rhys Bower is an aspiring local developer
  working on a number of personal programming
  projects. Rhys will be studying Computer Science at UBC next year.
image: img/portfolio.jpg
copyright: Copyright © 2015 Rhys Bower. All rights reserved.
permalink: /:year/:month/:title/
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
