# Site settings
title: Rhys Bower
author: Rhys Bower
email: bowerrhys@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rhys Bower is an aspiring local developer
  working on a number of personal programming
  projects. Rhys will be studying Computer Science at UBC next year.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:title/
url: "http://www.rhysbower.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
